#!/bin/bash
#
# Automatically sync folders across different operating systems
# Script for various operations with flags --add, --list and --remove
#
# Copyright (C)   2016    Madhav Datt
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#

# Add new pair of directories to sync
if [[ $# == 3 ]] && [[ $1 == "--add" ]]
then
    ./syncos "$2" "$3"

# List all directories being syncos'ed
elif [[ $# == 1 ]] && [[ $1 == "--list" ]]
then


# Stop syncing directories
elif [[ $# == 3 ]] && [[ $1 == "--remove" ]]
then


else
    printf "            syncos Copyright (C) 2016 by Madhav Datt
            Website: https://github.com/madhav-datt/syncos
            syncos comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
            are welcome to redistribute it under certain conditions.  See the GNU
            General Public Licence for details.

            Usage: syncos --add ... DIRECTORY-1... DIRECTORY-2
              or   syncos --list
              or   syncos --remove ... DIRECTORY-1... DIRECTORY-2

            DIRECTORY-1 is path to directory on primary (Linux) OS
            DIRECTORY-2 is path to directory on secondary OS

            Options
                --add               add pair of directories across OSs to sync
                --list              list all directories currently being synced
                --remove            remove and stop syncing pair of directories \n\n
            ";
fi
