#!/bin/bash
#
# Automatically sync folders across different operating systems
# Designed for dual/multi-boot systems with atleast one OS being a Linux flavor
#
# Copyright (C)   2016    Madhav Datt
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#

# Directory sync without deletion
# Sync once per minute using rsync
if [[ $# == 2 ]]
then
    # Build absolute paths for directory $2
    # Directory path $2 passed by the user is relative to C:// of Windows OS
    # Example: $2 = Users//Madhav//Desktop//Work
    WIN_OS_DIR="/mnt/""$2"

    # Check is directories $1 and $2 exist
    # Can handle both hardlinks and symlinks
    if [[ -d "$1" ]] && [[ -d "$WIN_OS_DIR" ]]
    then
        # Add rsync commands to crontab
        # Write out current crontab to temporary file
        crontab -l > tmp_cron

        # Echo new cron job into temporary cron file
        echo "* * * * * rsync -a $1/ $WIN_OS_DIR/" >> tmp_cron
        echo "* * * * * rsync -a $WIN_OS_DIR/ $1/" >> tmp_cron

        # Install new cron file
        crontab tmp_cron
        rm tmp_cron
    else
        printf "Directories $1 or $2 not found - syncos failed \n";
    fi

# Check for number of arguments passed while executing script
# Reject if exactly 2 arguments are not present
else
    # Delete any files that are in OS2_Directory and not in OS1_Directory
    printf "Usage: syncos folder/path/OS1_Directory folder/path/OS2_Directory \n";
fi
