#!/bin/bash
#
# Automatically sync folders across different operating systems
# Script for various operations with flags --add, --list and --remove
#
# Copyright (C)   2016    Madhav Datt
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#

# Add new pair of directories to sync
if [[ $# == 3 ]] && [[ $1 == "--add" ]]
then
    ./syncos "$2" "$3"

# List all directories being syncos'ed
elif [[ $# == 1 ]] && [[ $1 == "--list" ]]
then
    if [[ -f "syncos_track.txt" ]]
    then
        cat syncos_track.txt
    else
        printf "No directories added for syncing yet \n";
    fi

# Stop syncing directories
elif [[ $# == 3 ]] && [[ $1 == "--remove" ]]
then
    ./syncos_rm "$2" "$3"

# Display help if incorrect OPTION used
else
    printf "syncos Copyright (C) 2016 by Madhav Datt \n";
    printf "Website: https://github.com/madhav-datt/syncos \n";
    printf "syncos comes with ABSOLUTELY NO WARRANTY.  This is free software, and you \n";
    printf "are welcome to redistribute it under certain conditions.  See the GNU \n";
    printf "General Public Licence for details. \n\n";

    printf "Usage: syncos --add ... DIRECTORY-1... DIRECTORY-2 \n";
    printf "  or   syncos --list \n";
    printf "  or   syncos --remove ... DIRECTORY-1... DIRECTORY-2 \n\n";

    printf "DIRECTORY-1 is path to directory on primary (Linux) OS \n";
    printf "DIRECTORY-2 is path to directory on secondary OS \n\n";

    printf "Options \n"
    printf "    --add               add pair of directories across OSs to sync \n";
    printf "    --list              list all directories currently being synced \n";
    printf "    --remove            remove and stop syncing pair of directories \n\n";
fi
